### ISSUE TITLE
Package structure

### ISSUE THREAD

**Issue by izhangzhihao** [ThoughtWorksInc/DeepLearning.scala#32]
- deeplearning
  - package
    - implicit cases
  - Tape
  - Lift
  - tapefactories
  - math
  - logs
  - differentiable
    - package
      - type Float
      - `type Double = Do[_ <: Tape.Aux[scala.Double, scala.Double]]` / `type Double = Do[Tape.Aux[scala.Double, scala.Double]]`
      - type Any = Do[_ <: Tape.Aux[scala.Any, scala.Nothing]]
    - Any
      - AnyOps
        - predict
        - train
    - Float
    - Double
    - INDArray

- raii
  - resourcet
    - ResourceT
    - Releasable
  - sharedops
    - SharedOps
  - future
    - Do
  - sde
    - raii
    - `do`

- tryt

remove CovariantT
remove EitherTNondeterminism
remove FreeTParallelApplicative
remvoe KleisliParallelApplicative

**Comment by Atry** [comment]
Some thought on names:

 * `sharedops` => `shared`
 * `logrecords` => `logs`
 * `polyfunctions` => `math`, so we can use `com.thoughtworks.deeplearning.math.exp(2.4)`, like `scala.math.exp(2.4)`.

**Comment by izhangzhihao** [comment]
consider rename `DifferentiableNumericFunctions`

**Comment by Atry** [comment]
`managed` and `unmanaged` are bad names because they may confuse C# people

**Comment by izhangzhihao** [comment]
consider rename `FloatTape` & etc

**Comment by Atry** [comment]
`future` is not a good name because `Do` is an opacity type, and we will change the implementation of `Do` so it will not depends on `scalaz.concurrent.Future` any more.

**Comment by Atry** [comment]
Maybe `future` => `async`
